from colorama import init, Fore, Back

init()
FORE_RED = Fore.LIGHTRED_EX
FORE_GREEN = Fore.LIGHTGREEN_EX
FORE_CYAN = Fore.LIGHTCYAN_EX
FORE_YELLOW = Fore.LIGHTYELLOW_EX
FORE_WHITE = Fore.WHITE
FORE_BLACK = Fore.BLACK

BG_GREEN = Back.LIGHTGREEN_EX
BG_RED = Back.LIGHTRED_EX
BG_CYAN = Back.LIGHTCYAN_EX
BG_YELLOW = Back.LIGHTYELLOW_EX